services:
    resource.controller.abstract:
        class: Igdr\Bundle\ResourceBundle\Controller\ResourceController
        calls:
            - [setContainer, [@service_container]]

    resource.controller.configuration_factory:
        class: Igdr\Bundle\ResourceBundle\Controller\ConfigurationFactory
        arguments: [@request_stack, %igdr_resource.config.defaults%]
        calls:
            - [setManagerFactory, [@igdr_manager.manager.factory]]